// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ngk3_weather_api.Models;

namespace ngk3_weather_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211217114559_SeedObservationsMigration")]
    partial class SeedObservationsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ngk3_weather_api.Models.WeatherObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pressure")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("WeatherStationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeatherStationId");

                    b.ToTable("WeatherObservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 12, 17, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = 30.2m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 12, 17, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = 31m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 12, 17, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = 34m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 12, 16, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = 20m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 12, 16, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = 24m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 12, 16, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = 27m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 12, 18, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = 11m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2021, 12, 18, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = 12m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2021, 12, 18, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = 13m,
                            WeatherStationId = 1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2021, 12, 17, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = -30.2m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2021, 12, 17, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = -31m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2021, 12, 17, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = -34m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2021, 12, 16, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = -20m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2021, 12, 16, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = -24m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2021, 12, 16, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = -27m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2021, 12, 18, 12, 21, 8, 718, DateTimeKind.Unspecified).AddTicks(1648),
                            Humidity = 35L,
                            Pressure = 1100.1m,
                            Temperature = -11m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2021, 12, 18, 11, 44, 5, 325, DateTimeKind.Unspecified).AddTicks(8526),
                            Humidity = 19L,
                            Pressure = 1001.2m,
                            Temperature = -12m,
                            WeatherStationId = 2
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2021, 12, 18, 11, 39, 18, 279, DateTimeKind.Unspecified).AddTicks(433),
                            Humidity = 11L,
                            Pressure = 1011m,
                            Temperature = -13m,
                            WeatherStationId = 2
                        });
                });

            modelBuilder.Entity("ngk3_weather_api.Models.WeatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 56.234153999999997,
                            Longitude = 10.238569999999999,
                            Name = "Lystrup",
                            Password = "$2a$11$I.7FU5SjYL/fXL3Rbh8pnu3kJ3tuEZfx3CLcw47PTcddVnk7O0us.",
                            Username = "lystrup1"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 45.572113999999999,
                            Longitude = 6.8293480000000004,
                            Name = "Les Arcs",
                            Password = "$2a$11$ZXERkH4BEl904IDO.T5rdO2cggyRBIkkguIeoCh2zgxLDiz24CGB.",
                            Username = "lesarcs1"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = -53.093660999999997,
                            Longitude = 73.527350999999996,
                            Name = "Heard Island & McDonald Islands",
                            Password = "$2a$11$YDRRbSpTeuCpUI4iYXSrM.P5EPDk1uC17TVEl.OmD/6nXfI6cedta",
                            Username = "mcd1"
                        });
                });

            modelBuilder.Entity("ngk3_weather_api.Models.WeatherObservation", b =>
                {
                    b.HasOne("ngk3_weather_api.Models.WeatherStation", "WeatherStation")
                        .WithMany("WeatherObservations")
                        .HasForeignKey("WeatherStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("ngk3_weather_api.Models.WeatherStation", b =>
                {
                    b.Navigation("WeatherObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
